#!/usr/bin/env bash

CHOICE=/tmp/background-choice

cd $HOME/Pictures/Backgrounds

pic=`imv .`

echo $pic > $CHOICE

if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
  swww img $pic --transition-type center
else
  feh --no-fehbg --bg-fill $pic
fi
