#!/usr/bin/env bash

sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
nohup /usr/lib/xdg-desktop-portal-hyprland > /dev/null
sleep 2
/usr/lib/xdg-desktop-portal > /dev/null
